### ISSUE TITLE
The `.policy(resource)` helper method uses the default policy adapter rather than the namespaces

### ISSUE THREAD

**Issue by Bastes** [activeadmin/activeadmin#6144]
# Description

I have two ActiveAdmin namespaces:
```ruby
# in config/initializers/active_admin.rb
config.namespace :admin do |admin|
  ..
end

config.namespace :other_admin do |admin|
   other_admin.authorization_adapter = OtherAdmin::PunditAdapter
end
```

This `OtherAdmin::PunditAdapter` is a custom-made adapter that takes policies specific to this namespace instead of the standard ones.

In the `index` view of one of my resources, I want to keep a field from view of users who can't access it:
```ruby
# in app/admin/other_admin/the_resource.rb
ActiveAdmin.register TheResource, namespace: :other_admin do
  ...
  index as: :table do
    ..
    column(:the_field) do |the_resource|
      next unless policy(the_resource).the_field?

      the_resouce.the_field
    end
  end
end
```

The problem is that the `.policy(..)` helper method does not use the `other_admin` namespace specific adapter but pundit's `lib/pundit.rb` modules' `.pundit(..)` method, giving me the wrong policy for the resource in this context.

I would expect the `.policy(..)` helper to use that namespaces adapter.

### How to reproduce

I will provide a sample app for reproduction purpose as soon as possible.

**Comment by Bastes** [comment]
Tried yesterday all evening: I can't seem to be able to reproduce in a new app (same relevant gem versions, same mechanic, different results). The stack does not seem able to access the `.policy(..)` method from pundit's `lib/pundit.rb` for some reason.

I will try to find what makes the difference when I can but I can't dig further just now.

**Comment by Bastes** [comment]
Ok, you can ignore this issue: it had to do with our app including the `Pundit` module an relying on it as if it was ActiveAdmin's adapters. Sorry for the noise.

**Comment by rjherrera** [comment]
Hi there @Bastes ! Could you share your `OtherAdmin::PunditAdapter`? I'm trying to separate policies between namespaces but setting the `pundit_default_policy` or `pundit_policy_namespace` inside the namespace block in the initializer does not work. Thnak you!

**Comment by Bastes** [comment]
Hey @rjherrera :) sorry I can't do that anymore. The code belongs to a company I used to work for and I have changed about a year ago, I don't have access to it anymore. But maybe I can help in another way?

**Comment by rjherrera** [comment]
Thank you for the answer @Bastes! No worries, I understand perfectly. 

Based on your original issue, I think maybe you can help me. The thing I'm trying to do is to have separate policies for separate namespaces in my app. I described my issue with more detail [here](https://github.com/activeadmin/activeadmin/issues/6979), however, I was thinking that maybe using a custom pundit adapter may be an alternative way to go, as you did. Thanks in advance!

**Comment by Bastes** [comment]
Well, using different adapters based on namespace should work according to the docs:
https://activeadmin.info/13-authorization-adapter.html

And, memory serves, that was what me and my team were doing at the time.

So, what you were describing in your issue should be working, assuming you're at the same version the doc is based on?

**Comment by rjherrera** [comment]
Hi @Bastes thank you! And sorry for the late answer. Yes, I thought that namespacing pundit configuration should work as shown there, but it fails in terms of the pundit specific configs. 

I think using a specific custom adapter mimicking the Pundit one for each namespace (as you did), but forcing it to consider the namespace config will solve my issue. It's a shame it does not work with the built-in `pundit_policy_namespace` config but if it is solvable, I'm happy.

Thanks for your time and input!

**Comment by Bastes** [comment]
As long as it works for you :slightly_smiling_face: good job and good luck with what's next.

**Comment by senid231** [comment]
problem still exists in ActiveAdmin version `3.2.2`

here's my small fix at `config/initializers/active_admin.rb`

```ruby
# frozen_string_literal: true

require 'active_admin/pundit_adapter'
ActiveAdmin::PunditAdapter.class_eval do
  def default_policy_class
    resource.namespace.pundit_default_policy && resource.namespace.pundit_default_policy.constantize
  end

  def default_policy_namespace
    resource.namespace.pundit_policy_namespace
  end
end

ActiveAdmin.setup do |config|
  ...

  config.namespace :admin do |admin|
    admin.authorization_adapter = ActiveAdmin::PunditAdapter
    admin.pundit_default_policy = 'ApplicationPolicy'
    ...
  end

  config.namespace :other_admin do |other_admin|
    # uses default policy
    ...
  end
end
```
